name: lens-backend-app

services:
  backend:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_OWNER:-lensexe}/lens-backend:${IMAGE_TAG:-latest}
    pull_policy: always
    env_file:
      - stack.env
    ports:
      - '${BACKEND_HOST_PORT:-3000}:3000'
    networks:
      - lens-network
    restart: unless-stopped

networks:
  lens-network:
    external: true
    name: lens-network
